version: "3.3"

services:
  mongodb:
    image: mongo:6.0.12-rc1
    restart: unless-stopped
    container_name: mongodb
    environment:
      TZ: Asia/Ho_Chi_Minh
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    networks:
      - mongonw
    volumes:
      - /dockerd/mongodb_6.0.12:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "mongodb:mongodb"
    depends_on:
      - mongodb
    environment:
      TZ: Asia/Ho_Chi_Minh
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongodb:27017/
    networks:
      - mongonw
networks:
  mongonw: